export const skillOptions = [
  "Resume Writing",
  "Interviewing",
  "Networking",
  "LinkedIn Proficiency",
  "Time Management",
  "Research Skills",
  "Communication Skills",
  "Problem Solving",
  "Adaptability",
  "Teamwork",
  "Attention to Detail",
  "Critical Thinking",
  "Presentation Skills",
  "Negotiation",
  "Project Management",
  "Active Listening",
  "Emotional Intelligence",
  "Conflict Resolution",
  "Public Speaking",
  "Data Analysis",
  "Creative Thinking",
  "Technical Proficiency",
  "Sales Skills",
  "Customer Service",
  "Marketing Skills",
  "Social Media Management",
  "Content Creation",
  "Copywriting",
  "Strategic Planning",
  "Financial Analysis",
  "Budgeting",
  "Leadership",
  "Mentoring",
  "Coaching",
  "Decision Making",
  "Research Methodologies",
  "Process Improvement",
  "Risk Management",
  "Compliance Knowledge",
  "Quality Assurance",
  "Product Development",
  "Business Development",
  "Supply Chain Management",
  "Inventory Management",
  "Vendor Management",
  "Multitasking",
  "Cultural Awareness",
  "Analytical Thinking",
  "Database Management",
  "Software Proficiency",
  "HTML",
  "CSS",
  "JavaScript",
  "Python",
  "Microsoft Excel",
  "Microsoft Word",
  "Microsoft PowerPoint",
  "Google Workspace",
  "Agile Methodologies",
  "Lean Principles",
  "Change Management",
  "Digital Marketing",
  "SEO Knowledge",
  "Email Marketing",
  "Brand Management",
  "Graphic Design",
  "User Experience (UX)",
  "User Interface (UI) Design",
  "Web Development",
  "Mobile App Development",
  "Cloud Computing",
  "Cybersecurity Awareness",
  "Networking Skills",
  "Machine Learning",
  "Artificial Intelligence",
  "Customer Relationship Management (CRM)",
  "Enterprise Resource Planning (ERP)",
  "Video Editing",
  "Photography",
  "Event Planning",
  "Writing Skills",
  "Editing Skills",
  "Social Skills",
  "Persuasion Skills",
  "Presentation Software Proficiency",
  "Time Zone Awareness",
  "Global Awareness",
  "Intellectual Curiosity",
  "Stress Management",
  "Work Ethic",
  "Integrity",
  "Initiative",
  "Self-Motivation",
  "Goal Setting",
  "Adaptation to Technology",
  "Patience",
  "Flexibility",
  "Crisis Management",
  "Mentorship",
  "Collaboration",
  "Innovation",
  "Networking Events Participation",
  "Industry Knowledge",
  "Professional Development",
  "Programming Languages",
  "Java",
  "Python",
  "C++",
  "JavaScript",
  "Ruby",
  "Go",
  "Swift",
  "Kotlin",
  "C#",
  "PHP",
  "HTML",
  "CSS",
  "SQL",
  "Version Control (Git)",
  "API Development",
  "RESTful Services",
  "GraphQL",
  "Microservices Architecture",
  "Agile Methodologies",
  "Scrum",
  "Kanban",
  "Software Development Life Cycle (SDLC)",
  "Object-Oriented Programming (OOP)",
  "Functional Programming",
  "Test-Driven Development (TDD)",
  "Behavior-Driven Development (BDD)",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "Cloud Computing (AWS, Azure, Google Cloud)",
  "Containerization (Docker, Kubernetes)",
  "DevOps Practices",
  "Database Management Systems (MySQL, PostgreSQL, MongoDB)",
  "Data Structures and Algorithms",
  "System Design",
  "Debugging Skills",
  "Performance Optimization",
  "Code Review",
  "User Interface (UI) Design",
  "User Experience (UX) Principles",
  "Web Development Frameworks (React, Angular, Vue.js)",
  "Mobile App Development (iOS, Android)",
  "Game Development",
  "Software Testing (Unit Testing, Integration Testing)",
  "Security Best Practices",
  "Networking Concepts",
  "Agile Estimation and Planning",
  "Technical Documentation",
  "Project Management Tools (JIRA, Trello)",
  "Collaboration Tools (Slack, Microsoft Teams)",
  "Cross-Platform Development",
  "Machine Learning Basics",
  "Data Visualization",
  "Version Control Workflows",
  "Software Architecture Patterns",
  "Infrastructure as Code (IaC)",
  "Scripting Languages (Bash, PowerShell)",
  "Automation Tools",
  "Code Quality Tools (Linting, Static Analysis)",
  "Open Source Contributions",
  "Technical Blogging",
  "Community Engagement",
  "Microsoft Word",
  "Microsoft Excel",
  "Microsoft PowerPoint",
  "Microsoft Outlook",
  "Google Docs",
  "Google Sheets",
  "Google Slides",
  "Microsoft Access",
  "Adobe Acrobat",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Canva",
  "Trello",
  "Slack",
  "Zoom",
  "Microsoft Teams",
  "Dropbox",
  "OneDrive",
  "Asana",
  "Notion",
  "Evernote",
  "SurveyMonkey",
  "Mailchimp",
  "CRM Software (Salesforce, HubSpot)",
  "Video Conferencing Tools (Skype, Webex)",
  "Social Media Platforms (Facebook, LinkedIn, Twitter)",
  "Content Management Systems (WordPress, Joomla)",
  "HTML Basics",
  "CSS Basics",
  "Basic SEO Tools (Google Analytics, SEMrush)",
  "Project Management Software (JIRA, ClickUp)",
  "Time Tracking Software (Toggl, Harvest)",
  "Accounting Software (QuickBooks, FreshBooks)",
  "Email Management Tools",
  "File Sharing Tools (Google Drive, Box)",
  "Presentation Software (Prezi, Keynote)",
  "Data Visualization Tools (Tableau, Power BI)",
  "Digital Note-Taking Tools (Microsoft OneNote, Notability)",
  "E-learning Platforms (Coursera, Udemy)",
  "Basic Graphic Design Skills",
  "Website Builders (Wix, Squarespace)",
  "Virtual Whiteboards (Miro, Jamboard)",
  "Mind Mapping Software (MindMeister, XMind)",
  "Remote Desktop Software (TeamViewer, AnyDesk)",
  "Basic Programming (Scratch, HTML/CSS)",
  "Basic Video Editing (iMovie, Adobe Premiere Rush)",
  "Customer Support Software (Zendesk, Freshdesk)",
  "Survey and Polling Tools",
  "Basic Data Entry Skills",
  "Basic Hardware Troubleshooting",
  "Cloud Storage Management",
  "Accessibility Tools",
  "Basic Cybersecurity Awareness",
  "Desktop Publishing Software (Microsoft Publisher)",
  "Online Collaboration Tools",
  "Basic Coding Concepts (Python, JavaScript basics)",
  "Email Etiquette",
  "Digital Marketing Basics",
  "Content Editing Tools (Grammarly, Hemingway)",
  "Online Payment Platforms (PayPal, Venmo)",
  "Voice-over Software (Audacity)",
  "Text-to-Speech Tools",
  "Digital Art Software (Procreate, CorelDRAW)"
]